# Generated by Django 4.0.3 on 2022-03-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_education_research_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_study_destination',
        ),
    ]
