# Generated by Django 4.0.3 on 2022-03-26 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_user_preferred_study_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='multiple_select_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Multiple_select_study_destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_study_destination', models.CharField(blank=True, choices=[('USA', 'USA'), ('CANADA', 'Canada'), ('UK', 'UK'), ('INDIA', 'India'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('AUSTRALIA', 'Australia')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
