# Generated by Django 4.0.3 on 2022-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_user_multiple_select_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='single_select_destination',
            field=models.BooleanField(default=True),
        ),
    ]
