# Generated by Django 4.0.3 on 2022-03-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_user_single_select_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='multiple_select_destination',
        ),
        migrations.RemoveField(
            model_name='user',
            name='single_select_destination',
        ),
        migrations.DeleteModel(
            name='Multiple_select_study_destination',
        ),
    ]
