# Generated by Django 4.0.3 on 2022-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_user_multiple_select_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_study_destination',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('CANADA', 'Canada'), ('UK', 'UK'), ('INDIA', 'India'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('AUSTRALIA', 'Australia')], max_length=255, null=True),
        ),
    ]
