# Generated by Django 4.0.3 on 2022-03-28 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_education_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_study_destination',
        ),
        migrations.CreateModel(
            name='MultipleSelectPreferredStudyDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_study_destination', models.CharField(blank=True, choices=[('USA', 'USA'), ('CANADA', 'Canada'), ('UK', 'UK'), ('INDIA', 'India'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('AUSTRALIA', 'Australia')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_preferred_study_destination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
