# Generated by Django 4.0.3 on 2022-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_offered', models.CharField(choices=[('Master by Research', 'Master by Research'), ('Phd', 'Phd'), ('Post Doctorate', 'Post Doctorate')], max_length=255)),
                ('scholarship_provided', models.BooleanField(default=False)),
                ('research_lab', models.TextField(blank=True, null=True)),
                ('minimum_qualification_required', models.CharField(max_length=30)),
                ('latest_research_description', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'ProfessorProfile',
            },
        ),
    ]
