# Generated by Django 4.0.3 on 2022-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_remove_professorprofile_research_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='minimum_gpa_required',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
