# Generated by Django 4.0.3 on 2022-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_professorprofile_minimum_gpa_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='is_accepting_international_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='is_domestic_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='preferred_country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('CANADA', 'Canada'), ('UK', 'UK'), ('INDIA', 'India'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('AUSTRALIA', 'Australia')], max_length=255, null=True),
        ),
    ]
