# Generated by Django 4.0.3 on 2022-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_professorprofile_is_accepting_international_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='home_page_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
